### ISSUE TITLE
这个项目的废弃了吗

### ISSUE THREAD

**Issue by shang7053** [mayanhui/ella#9]
hbase jmx的bean已经变了，ella无法正常运行了

**Comment by mayanhui** [comment]
已经有年多时间没有再更新，精力不够持续更新，你用的HBase是什么版本？ 1.* 还是 0.9*？JMX的Java Bean从 0.96就改动了，现在只支持0.94.*的版本 Hadoop对应版本是1.*.   可以汇总一下现阶段大家使用的针对性版本，再启动持续更新的Roadmap。 后面也有类似 @shang7053 问题，可以再下面评论，讲HBase、Hadoop的版本都备注一下。

**Comment by jonny-wang** [comment]
我这边用的hbase0.96 hadoop2.2 发现jmx变了，我这这边的做法是用hbase admin替换的jmx的数据获取，实现了监控功能，不知道这样做有没有问题，希望大家继续讨论

**Comment by mayanhui** [comment]
@jonny-wang 你使用的是协议改动后的JMX吧，如果测试没有问题理论上是可以的。能简单总结一下架构改动的要点吗，给大家提供一些信息，避免重复验证。
另，0.96后的版本应该将双master的监控加入进去。

**Comment by jonny-wang** [comment]
@mayanhui 我是这样改的，我是将jmx获取的信息改成了用hbase api进行获取，0.96的jmx我看了一下，有些东西在jmx中拿不到

**Comment by nervalpoet** [comment]
我用的是 hbase1.2.3 hadoop 2.6.5,,,,,,,今天装完发现不能用。

**Comment by nervalpoet** [comment]
这是个挺好的项目，建议群主不要废弃掉，搞个qq群。可以一直讨论交流，完善。

**Comment by mayanhui** [comment]
没有废弃，前段区区在下忙着琐事，已经启动版本升级和功能迭代，这段时间会持续输出，谢谢诸位的建议和鞭策~
